### ISSUE TITLE
RTNETLINK answers: Permission denied

### ISSUE THREAD

**Issue by aquada** [tempestnano/docker-transmission-openvpn#1]
**Describe the problem**
I am getting 2 Errors in the docker compose log.

1. Error: argument "0.0.0.0" is wrong: "metric" value is invalid
2. RTNETLINK answers: Permission denied

```
docker-compose.yml
services:

    transmission-openvpn:

        volumes:

            - '/home/pi/docker/transmission-openvpn/ovpn/default.ovpn:/etc/openvpn/custom/default.ovpn'

            - '/home/pi/docker/transmission-openvpn/data:/data'

            - '/etc/localtime:/etc/localtime:ro'

        environment:

            - CREATE_TUN_DEVICE=true

            - OPENVPN_PROVIDER=CUSTOM

            - OPENVPN_CONFIG=default 

            - WEBPROXY_ENABLED=false

            - LOCAL_NETWORK=192.168.0.0/24

        cap_add:

            - NET_ADMIN

        logging:

            driver: json-file

            options:

                max-size: 10m

        ports:

            - '9091:9091'

        image: jstrader/transmission-openvpn
```

**Logs**
```
transmission-openvpn_1  | Using OpenVPN provider: CUSTOM
transmission-openvpn_1  | Starting OpenVPN using config default.ovpn
transmission-openvpn_1  | Found existing OPENVPN credentials...
transmission-openvpn_1  | Error: argument "0.0.0.0" is wrong: "metric" value is invalid
transmission-openvpn_1  | 
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 OpenVPN 2.4.7 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  5 2019
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]5.2.79.218:1194
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 Socket Buffers: R=[163840->163840] S=[163840->163840]
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 UDP link local: (not bound)
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 UDP link remote: [AF_INET]5.2.79.218:1194
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 TLS: Initial packet from [AF_INET]5.2.79.218:1194, sid=d84a63c7 d32a2136
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 VERIFY OK: depth=1, CN=cn_djAsPByXZxkhynXf
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 VERIFY KU OK
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 Validating certificate extended key usage
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 VERIFY EKU OK
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 VERIFY X509NAME OK: CN=server_OUCnWRtjl4JbiZjz
transmission-openvpn_1  | Mon Apr 13 14:10:07 2020 VERIFY OK: depth=0, CN=server_OUCnWRtjl4JbiZjz
transmission-openvpn_1  | Mon Apr 13 14:10:08 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-ECDSA-AES128-GCM-SHA256, 256 bit EC, curve: prime256v1
transmission-openvpn_1  | Mon Apr 13 14:10:08 2020 [server_OUCnWRtjl4JbiZjz] Peer Connection Initiated with [AF_INET]5.2.79.218:1194
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 SENT CONTROL [server_OUCnWRtjl4JbiZjz]: 'PUSH_REQUEST' (status=1)
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 1.0.0.1,dhcp-option DNS 1.1.1.1,redirect-gateway def1 bypass-dhcp,tun-ipv6,route-ipv6 2000::/3,redirect-gateway ipv6,tun-ipv6,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig-ipv6 fd42:42:42:42::1000/112 fd42:42:42:42::1,ifconfig 10.8.0.2 255.255.255.0,peer-id 2,cipher AES-128-GCM'
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 OPTIONS IMPORT: timers and/or timeouts modified
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 OPTIONS IMPORT: --ifconfig/up options modified
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 OPTIONS IMPORT: route options modified
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 OPTIONS IMPORT: route-related options modified
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 OPTIONS IMPORT: peer-id set
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 OPTIONS IMPORT: adjusting link_mtu to 1624
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 OPTIONS IMPORT: data channel crypto options modified
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 Outgoing Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 Incoming Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 ROUTE_GATEWAY 172.18.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:12:00:02
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 GDG6: remote_host_ipv6=n/a
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 ROUTE6: default_gateway=UNDEF
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 TUN/TAP device tun0 opened
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 TUN/TAP TX queue length set to 100
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 /sbin/ip link set dev tun0 up mtu 1500
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 /sbin/ip addr add dev tun0 10.8.0.2/24 broadcast 10.8.0.255
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 /sbin/ip -6 addr add fd42:42:42:42::1000/112 dev tun0
transmission-openvpn_1  | RTNETLINK answers: Permission denied
transmission-openvpn_1  | Mon Apr 13 14:10:09 2020 Linux ip -6 addr add failed: external program exited with error status: 2

```

**Host system:**
 Raspberry Pi 2 Buster

Which version of Docker are you using? --> 

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:35:24 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:22 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```
